production:
  SITE_NAME=Southwest Checkin
  SITE_URL=http://138.68.53.232:3000
  ASSET_HOST=http://138.68.53.232:3000
  MAILER_DEFAULT_FROM_EMAIL=test@localhost:3000
  MAILER_DEFAULT_REPLY_TO=test@localhost:3000
  DEPLOY_BRANCH=master
  DEPLOY_USER=deploy
  DEPLOY_PORT=22
  MAILER_ADDRESS=
  MAILER_DOMAIN=
  MAILER_USERNAME=
  MAILER_PASSWORD=
  MAILER_DEFAULT_HOST=
  DEPLOY_DOMAIN=
  DEPLOY_TO=
  DEPLOY_REPOSITORY=
  DEPLOY_USE_RBENV=true

