default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  username: postgres
  password: postgres

development:
  <<: *default
  database: southwest-checkin_development

test:
  <<: *default
  database: southwest-checkin_test

production:
  <<: *default
  database: southwest_checkin_production
  